# Generated by Django 5.2.1 on 2025-06-02 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="Created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
